name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install packages
        run: npm ci
        
      - name: Create Windows cert File
        id: create_pfx
        if: matrix.os == 'windows-latest'
        uses: timheuer/base64-to-file@v1
        with:
          filename: certificate.pfx
          encodedString: ${{ secrets.BKFIYUR }}

      - name: Run Electron Builder
        run: npx electron-builder --publish=never
        env:
          CSC_LINK: ${{ steps.create_pfx.outputs.filePath }}
          CSC_KEY_PASSWORD: ${{ secrets.PUIYDBD }}
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            dist
            !dist/*.blockmap
            !dist/*.yml
            !dist/win-unpacked
            !dist/linux-unpacked
            !dist/.icon-set
            !dist/mac
            !dist/.cache
          retention-days: 1
